### ISSUE TITLE
Night-version cityscapes 

### ISSUE THREAD

**Issue by daeunni** [jgkwak95/AU-GAN#10]
Hi, thanks for your nice work :) 
I was wondering if I can make a night version of the cityscapes dataset using this model. 

or just in case, do u have a night-version cityscapes dataset?

**Comment by jgkwak95** [comment]
Hi @daeunni , thanks for your attention. 

I haven't tried day->night with cityscape dataset, I think you can make the night version of cityscpaes datset with the pretrained model (which is trained w. BDD100K) 
But I think it does not bring optimal results because of the domain gap.

**Comment by jgkwak95** [comment]
Closed issue.

Feel free to reopen it.

**Comment by daeunni** [comment]
Thanks for your kind reply! Ill try it :)
