### ISSUE TITLE
The training results show discrepancies in terms of color or object positions.

### ISSUE THREAD

**Issue by ZHU-YU-MIN** [jgkwak95/AU-GAN#12]
I am currently training my own dataset for day-to-night image translation. 
However, the generated images produced during training do not accurately depict the transformation from night to day in the original images. 
The positions or colors of the generated objects are incorrect.
Could I ask how many epochs were set for the training, or are there other ways to improve this issue?

**Comment by jgkwak95** [comment]
> The positions or colors of the generated objects are incorrect.

Please check the resolutions of both domain's images.
