### ISSUE TITLE
Readme not up to date

### ISSUE THREAD

**Issue by vb87** [jgkwak95/AU-GAN#13]
This is a promising project, and could have some use cases, although a better and higher resolution models should be trained, and perhaps the algorithm tweaked.

I was unable to set it up nor run using the provided readme instructions, so here are the adjusted commands that I used to get it up and running on Windows, if the original author is no longer interested in this project, then someone could use this and perhaps fork a new repo and improve the project:

```
git clone https://github.com/jgkwak95/AU-GAN.git
cd AU-GAN
conda create -y --name augan python=3.6.7
conda activate augan
conda install tensorflow-gpu==1.15.0
pip install --no-cache-dir -r requirements.txt
conda install tensorflow-estimator==1.15.1
mkdir datasets
mkdir datasets\bdd100k
mkdir datasets\bdd100k\testA
```

place whatever night time images files you have in datasets\bdd100k\testA

can use this pretrained model: https://drive.google.com/file/d/1rvIF3yE9MwPWj0kD4IEstETyMQXYAHzr/view?usp=sharing
unzip to ./check/bdd_exp/bdd100k_256/

now run:
`python main.py --dataset_dir bdd100k --phase test --experiment_name bdd_exp --batch_size 1 --load_size 286 --fine_size 256
`
output is in .\check\bdd_exp\testa2b

**Comment by jgkwak95** [comment]
Hi, thanks for your attention,

It seems like the difference is the tensorflow version (1.14 -> 1.15)

This work was conducted under RTX 2080Ti,
and acturally it could support both tensorflow 1.14 and 1.15 
but I've never tried our code in Windows, thanks for sharing :)
