### ISSUE TITLE
Pretrained Model for testing on a single image.

### ISSUE THREAD

**Issue by Rodrigues-Royston** [jgkwak95/AU-GAN#2]
Thankyou for your amazing work. I was interested in the pre-trained model.
Is there a pre-trained model  available to convert a single image from night -> day. 
Thankyou for your time. Looking forward for your response.

**Comment by jgkwak95** [comment]
@Rodrigues-Royston Thanks for your attention. I will upload pre-trained model as soon as possible.

**Comment by PINTO0309** [comment]
I don't know if it will help you guys, but I've committed the demo code, optimized for ONNX, TFLite and other formats. Demo code contributed by community members.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/251_AU-GAN

![image](https://user-images.githubusercontent.com/33194443/152672814-96be38fa-2e42-4c73-a510-3c6252a6d75a.png)

**Comment by jgkwak95** [comment]
@PINTO0309  Thanks for your wonderful work!

**Comment by jgkwak95** [comment]
@PINTO0309  I updated Readme and linked to your github. If you don't want to, I'll delete that paragraph. 
Thank you again!

**Comment by PINTO0309** [comment]
I am honored. Thank you very much. :smile_cat:
