### ISSUE TITLE
Hello? Thank you for the awosome repository. My question is Can i use this to generate rainy,foggy and snowy datasets from a clear weather and can you help me providing a pretrained model for that if you have please? my email address is agmuas003@gmail.com. With regards.

### ISSUE THREAD

**Issue by tilahun12** [jgkwak95/AU-GAN#3]

**Comment by jgkwak95** [comment]
Sorry for the late reply.  Besides rainy or night, our model is also applicable to other environments (e.g., foggy, snowy) if you can define and construct dataset (clean vs. adverse). The original purpose of our model is to translate adverse weather to clear weather, but translation in the opposite direction (clear->adverse) is also possible for dataset generation.

**Comment by tilahun12** [comment]
when i tried to start the training It shows error 'CUDA OUT OF MEMORY' even with reduced batch size of 1. what is the possible solution please?
