### ISSUE TITLE
when i tried to start the training It shows error 'CUDA OUT OF MEMORY' even with reduced batch size of 1. what is the possible solution please?

### ISSUE THREAD

**Issue by tilahun12** [jgkwak95/AU-GAN#4]

**Comment by jgkwak95** [comment]
You might meet OOM if your gpu has small memory (in my case, i used 24GB one and also i checked our model can be trained with Alderley dataset on 11GB RAM GPU with batchsize 1. I suggest you to reduce the resolution of training image by changing training option (e.g., 1024x512 -> 512x256).

**Comment by tilahun12** [comment]
I use this command for training  python main.py  --dataset_dir bdd100k  --phase train --experiment_name bdd_exp --batch_size 1 --load_size 572 --fine_size 256 --use_uncertainty True 
![12](https://user-images.githubusercontent.com/50729468/167476951-9e657c6a-f866-4632-8def-0a39dca443df.PNG)

**Comment by jgkwak95** [comment]
Please check again that the training datasets (trainA & trainB) are loaded correctly.
In addition, modify the '--load_size' to 286 (572-->286) in your command line.
