### ISSUE TITLE
Alderley dataset

### ISSUE THREAD

**Issue by ejhung** [jgkwak95/AU-GAN#5]
Firstly, thank you for sharing your wonderful work.
I was about to try your project, but seems there is an unknown issue to the Alderley dataset. It is unavailable to access to the link. Also, I've tried to reach to the website via Google but seems the website itself has issues.
If possible, could you provide a link(e.g. Google drive) to access to the Alderley dataset you have?
Thank you.

**Comment by jgkwak95** [comment]
Hi, It seems that access to Alderley dataset is currently unavailable. I also tried, but couldn't  reach to the website. 
It seems impossible to share the dataset directly due to copyright issues. Please try BDD100K or other dataset.

**Comment by ejhung** [comment]
Thank you for the response.
