### ISSUE TITLE
Some strange results with the pre-trained file and BDD10K  dataset.

### ISSUE THREAD

**Issue by hellohaozheng** [jgkwak95/AU-GAN#6]
Thanks for your great work! I tried to reproduce your work. But I found some strange results with the pre-trained file and BDD10K dataset. @jgkwak95 

When the fine_size is set to 512, I got the black results:
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/74909571/195012615-b6a51fbc-ff32-49e6-a80d-2edcd073d7c0.png">

When the fine_size is set to 1024, I got the scary results:
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/74909571/195012663-75c2a8b0-676d-43d9-8f6d-e30ac0209b0c.png">

**Comment by jgkwak95** [comment]
Please check  'load_size' or 'fine_size'. you should give proper 'load_size' as well as 'fine_size'.  
For example,   test_img_size: 512x1024 --> load_size: 572 & fine_size: 512 .

**Comment by hellohaozheng** [comment]
@jgkwak95 Thanks for your reply. But I still got this black image in 'testa2b' folder.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/74909571/195240810-369dc58c-7b60-4e7a-97be-61c1151d9031.png">

The pre-trained file is [this](https://drive.google.com/file/d/1QUAAzFlL5Acdo0U-U-fMWXJ0fE1FG2wj/view?usp=sharing). I infer that it is something wrong with the file/
The files organization is like this:
<img width="294" alt="image" src="https://user-images.githubusercontent.com/74909571/195241132-53995285-b8ba-4bf5-9e00-ff988d6d3f19.png">

**Comment by jgkwak95** [comment]
Did you use the pretrained checkpoint? or your training version? 

The pretrained model is only for 256x512 images  (fine_size:256)
 Sorry for the confusion :(

**Comment by hellohaozheng** [comment]
Ohhh, got it.

**Comment by hellohaozheng** [comment]
Hello! I come back to enquire you how to train and infer the model correctly. I got such a confusing result both on your pretrained model and my training version.

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/74909571/196035623-ca3e4294-7e32-40b8-a97c-b491fbf4495b.png">

I follow your requirement and use such a command to test the model.
`python main.py --dataset_dir bdd100k --phase test --experiment_name bdd_exp --batch_size 1 --load_size 286 --fine_size 256`

 And It is for training.
`python main.py --dataset_dir bdd100k --phase train --experiment_name bdd_exp_2 --batch_size 8 --load_size 286 --fine_size 256 --use_uncertainty True`

Looking forward to your reply. Thanks you a lot!

**Comment by hellohaozheng** [comment]
Another problem is that the training doesn't converge with the above command. @jgkwak95 
<img width="798" alt="image" src="https://user-images.githubusercontent.com/74909571/196036418-8a73d51d-bf83-44de-acc5-37448c80b5e1.png">

**Comment by jgkwak95** [comment]
Hi @hellohaozheng, I think it's a problem with dataset construction.
However, it is curious to get strange results even with the pretrained model.
Also check the match of the experiment name. Judging from your question alone, the exeriment_name seems to be different.

Feel free to let me know if you have any problems!

**Comment by hellohaozheng** [comment]
I am so glad to receive your answer soon. @jgkwak95 I organized the dataset as follows.
![image](https://user-images.githubusercontent.com/74909571/196125334-9b427a7e-0788-407a-8672-40ff8d47ad88.png)
'A' class are rainy/night images, and 'B' class are sunny images.
I find here a work organizing the dataset BBD100k for your work. I used it to train the model but got the same problem.
https://github.com/ptrxpl/augan-forkgan-bdd-dataset

I want to ask you such a question: could I train or evaluate the model on BBD100K with fine_size = 256 and load_size = 286? They are 512 and 572 separately in your readme.

P.S. I used different experiment_name for training and evaluation separately.

**Comment by jgkwak95** [comment]
> I want to ask you such a question: could I train or evaluate the model on BBD100K with fine_size = 256 and load_size = 286? They are 512 and 572 separately in your readme.

The pretrained model is applicable only for 256 evaluation, not for 512. 
Training size and evaluation size should be same. If you want to get 512 image with our model,
you should train a  new model with 512 resol. (fine_size=512, load_size=572).

>'A' class are rainy/night images, and 'B' class are sunny images.

There seems to be no problem in dataset construction.

>P.S. I used different experiment_name for training and evaluation separately.

Why did you use different name?

**Comment by hellohaozheng** [comment]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/74909571/196161526-4a4c7976-975c-492f-a5cb-1a3cbff0e3e4.png">
Thanks firstly!
Because I put your pretrained model in the "bdd_exp" folder for evaluation on your model.
And I plan to train a new model from start, so I create a new folder "bdd_exp_2"
