### ISSUE TITLE
Cannot download pre-train model

### ISSUE THREAD

**Issue by pakcheera** [jgkwak95/AU-GAN#7]
Thanks @jgkwak95  for the interesting result. However, I cannot download pre-train model. Cloud you fix it?  
<img width="1201" alt="Screen Shot 2566-02-07 at 12 59 45" src="https://user-images.githubusercontent.com/72345015/217161342-5af6414a-b93f-4a08-8362-1179bb37d8dc.png">

**Comment by jgkwak95** [comment]
Hi @pakcheera, thanks for your attention.

The download link is blocked due to change of our school's mail server, 
But currently I don't have the checkpoint file because I changed my experimental computer last year. 
I will upload it after a new training.
