### ISSUE TITLE
Still Cannot download pre-train model

### ISSUE THREAD

**Issue by giserzy** [jgkwak95/AU-GAN#8]
dear authors, thanks for your contribution· for this filed, but now we still cannot download the pre-trained model, can you reshare it?

**Comment by jgkwak95** [comment]
The link of pretrained model is dead because of our institution's storage system change. 
Currently I'm in abroad so i cant access my local memory. 
I will upload a new pretrained model soon after a new training.

-jg

**Comment by jgkwak95** [comment]
Uploaded the pretrained model and i'll close the issue. 

Feel free to reopen it.
